FROM registry.console.rocks/buildbase:v1.0.0

ENV DAPPER_SOURCE /tmp/build
ENV DAPPER_DOCKER_SOCKET true
ENV DAPPER_ENV DRONE_BRANCH DRONE_COMMIT

WORKDIR ${DAPPER_SOURCE}

ENV PKG devops-demo-app
ENV PROJECT ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD [ "package" ]
