#!/bin/bash
set -e

export REPO=${REPO:-registry.console.rocks}
export PKG=${PKG:-devops-demo-app}

mkdir -p usr/bin usr/sbin
if [ -e ./scripts/$1 ]; then
    ./scripts/"$@"
else
    exec "$@"
fi

chown -R $DAPPER_UID:$DAPPER_GID .
