#!/bin/bash
set -e

source $(dirname $0)/version
source $(dirname $0)/package

docker push ${REPO}/${PKG}:${TAG}

echo Pushed ${REPO}/${PKG}:${TAG}

export

export PLUGIN_DOCKER_IMAGE=${REPO}/${PKG}:${TAG}
