#!/bin/bash

cd ${PROJECT}

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

GIT_COMMIT=$(git rev-parse --short HEAD)
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
GIT_TAG=$(git describe --tags --abbrev=0)


if [ -z "$DRONE_COMMIT" ]; then
    DRONE_COMMIT=$GIT_COMMIT
fi

if [ -z "$DRONE_BRANCH" ]; then
    DRONE_BRANCH=$GIT_BRANCH
fi

COMMIT=${DRONE_COMMIT:0:4}
BRANCH=${DRONE_BRANCH}
BUILD=$(git rev-list --count ${DRONE_COMMIT})

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION="${GIT_TAG}"
else
    VERSION="${GIT_TAG}${DIRTY}"
fi

if [ "${BRANCH}" != "master" ]; then
  VERSION="${VERSION}--${BRANCH}--${BUILD}--${COMMIT}"
fi

if [ -z "$ARCH" ]; then
    ARCH=amd64
fi

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

TAG=${TAG:-${VERSION}${SUFFIX}}

cd ${DAPPER_SOURCE}
